title: Avikshit Banerjee # your name (or website title) here
logo: "/images/round-frame.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with a Masters in Behavioural and Data Science and 2.5 years of professional experience as a software engineer utilizing AGILE methodologies along with hands-on experience in exploratory data analysis (EDA), data mining, data visualisation, machine learning, natural language processing (NLP), cognitive modelling and Bayesian/Frequentist inferential statistics. Decisive problem solver, utilizing principles of data science, behavioural science, and engineering for providing holistic and innovative solutions to complex problems.
  <br><br>
  MSc. Behavioural and Data Science @ The University of Warwick
  <br><br>
  <a href="https://www.linkedin.com/in/avikshit-banerjee/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
