title: Avikshit Banerjee # your name (or website title) here
logo: "/images/round-frame.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with 2.5 years of professional experience as a software engineer utilizing AGILE methodologies along with hands-on experience in Data mining, Data Visualisation, Machine Learning, NLP, Cognitive modelling and Bayesian/Frequentist inferential statistics.
  <br><br>
  MSc. Behavioural and Data Science
  The University of Warwick
  <br><br>
  <a href="https://www.linkedin.com/in/avikshit-banerjee/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/avikshit.banerjee#!/?newProfile=&activeTab=0/">View My Tableau Public Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
